version: "3"

services: 

  vernemq:
    container_name: vernemq-container
    image: vernemq/vernemq:1.10.3
    restart: always
    ports:
      - "1883:1883"
      - "8888:8888"
    logging:
      driver: none
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST: "0.0.0.0:1883"
      # Without authentication
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
      # Authentication with file
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
      # Authentication with Webhook
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: "on"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK1__HOOK: "auth_on_register"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK1__ENDPOINT: "http://collector:3030/auth"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK2__HOOK: "auth_on_publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK2__ENDPOINT: "http://collector:3030/auth-publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK3__HOOK: "on_publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK3__ENDPOINT: "http://collector:3030/publish"

  collector:
    container_name: collector-container
    restart: always
    image: lucaslui/collector-image:latest
    ports:
      - "3030:3030"
    depends_on:
      - vernemq
    environment:
      HOST: '0.0.0.0'
      PORT: 3030
      INFLUX_URL: https://us-east-1-1.aws.cloud2.influxdata.com
      ORG: hems-org
      BUCKET: hems-bucket
      TOKEN: rdHMyK4_GrLE4pk5nwTjijvSnkUuOX3JCYQX0jofIVYtHq-Jsxe4Xf8V35sLecJexJY2QCZ8g1Lwv1LrIsoHEg==
  
  backend: 
    container_name: backend-container
    restart: always
    image: lucaslui/backend-image-repository:latest
    ports:
      - "5050:5050"
    environment:
      HOST: '0.0.0.0'
      PORT: 5050
      MONGO_URL: "mongodb+srv://user:user1020304050@projetocopelcluster.gpwsi.mongodb.net/software-nuvem-db" 
      INFLUX_URL: https://us-east-1-1.aws.cloud2.influxdata.com
      INFLUX_TOKEN: rdHMyK4_GrLE4pk5nwTjijvSnkUuOX3JCYQX0jofIVYtHq-Jsxe4Xf8V35sLecJexJY2QCZ8g1Lwv1LrIsoHEg==
      INFLUX_ORG: hems-org
      INFLUX_BUCKET: hems-bucket

  frontend:
    container_name: frontend-container
    restart: always
    image: lucaslui/frontend-image:latest 
    ports:
      - "80:8080"
    depends_on:
      - backend
    environment:
      HOST: '0.0.0.0'
      PORT: 8080   
