version: "3"
services: 
  mongodb: 
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes: 
      - ./mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      MONGO_INITDB_DATABASE: software-nuvem-db
  
  influxdb:
    container_name: influx-container
    image: influxdb:latest
    restart: always
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup 
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: hems-org
      DOCKER_INFLUXDB_INIT_BUCKET: hems-bucket 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: i_OORQe_PBbaPFpCp75QS_EdqAIM77FJ2QrHo4Op25kzEvggITWHim8ab0OaG5zLIyrShQbvTbwrwq0dpADKgg==
  
  backend: 
    container_name: backend-container
    image: node:14
    working_dir: /usr/software-nuvem-backend/
    restart: always
    command: bash -c "npm install --only=production && npm install -D nodemon && npm run debug"
    volumes: 
      - ./dist/:/usr/software-nuvem-backend/dist/
      - ./package.json:/usr/software-nuvem-backend/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - "mongodb:mongodb"
      - "influxdb:influxdb"
    depends_on:
      - mongodb   
      - influxdb
    environment:
      MONGO_URL: mongodb://user:user1234@mongodb:27017/software-nuvem-db  
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: i_OORQe_PBbaPFpCp75QS_EdqAIM77FJ2QrHo4Op25kzEvggITWHim8ab0OaG5zLIyrShQbvTbwrwq0dpADKgg==
      INFLUX_ORG: hems-org
      INFLUX_BUCKET: hems-bucket
    

      