version: "3"

services: 
  mongo: 
    container_name: mongo-container
    image: mongo:4.2
    restart: always
    volumes: 
      - ./mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: rtdsp1020304050
      MONGO_INITDB_DATABASE: software-nuvem-db

  influxdb:
    container_name: influx-container
    image: influxdb:latest
    restart: always
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup 
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: rtdsp1020304050
      DOCKER_INFLUXDB_INIT_ORG: hems-org
      DOCKER_INFLUXDB_INIT_BUCKET: hems-bucket 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: i_OORQe_PBbaPFpCp75QS_EdqAIM77FJ2QrHo4Op25kzEvggITWHim8ab0OaG5zLIyrShQbvTbwrwq0dpADKgg==

  collector:
    container_name: collector-container
    restart: always
    build: "./"
    user: "node"
    ports:
      - "8081:8081"
    links:
      - "mongo:mongo"
      - "influxdb:influxdb"
    environment:
      NODE_ENV: production
      PORT: 8081
      HOST: '0.0.0.0'
      MONGO_URL: mongodb://user:user1020304050@mongo:27017/software-nuvem-db  
      INFLUX_URL: http://influxdb:8086
      ORG: hems-org
      BUCKET: hems-bucket
      TOKEN: i_OORQe_PBbaPFpCp75QS_EdqAIM77FJ2QrHo4Op25kzEvggITWHim8ab0OaG5zLIyrShQbvTbwrwq0dpADKgg==
    depends_on:
      - influxdb
      - mongo

  vernemq:
    container_name: vernemq-container
    image: vernemq/vernemq:1.10.3
    restart: always
    links:
      - "mongo:mongo"
      - "collector:collector"
    ports:
      - "1883:1883"
      - "8888:8888"
    depends_on:
      - collector
      - influxdb
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_LISTENER__TCP__LOCALHOST: "0.0.0.0:1883"
      # Without authentication
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "off"
      # Authentication with file
      DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD: "off"
      DOCKER_VERNEMQ_PLUGINS__VMQ_ACL: "off"
      # Authentication with MongoDB
      DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY: "off"
      # DOCKER_VERNEMQ_VMQ_DIVERSITY__AUTH_MONGODB__ENABLED: "on"
      # DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__HOST: "mongo"
      # DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__PORT: 27017
      # DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__LOGIN: user
      # DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__PASSWORD: user1020304050
      # DOCKER_VERNEMQ_VMQ_DIVERSITY__MONGODB__DATABASE: software-nuvem-db
      # Logs
      # DOCKER_VERNEMQ_LOG__CONSOLE: "console"
      # DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: "debug"
      # Webhooks
      DOCKER_VERNEMQ_PLUGINS__VMQ_WEBHOOKS: "on"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK1__HOOK: "auth_on_register"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK1__ENDPOINT: "http://collector:8081/auth"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK2__HOOK: "auth_on_publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK2__ENDPOINT: "http://collector:8081/auth-publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK3__HOOK: "on_publish"
      DOCKER_VERNEMQ_VMQ_WEBHOOKS__WEBHOOK3__ENDPOINT: "http://collector:8081/publish"
